### ISSUE TITLE
panic observed while pinging an IP address

### ISSUE THREAD

**Issue by simar7** [sparrc/go-ping#12]
Hello,

While using the go-ping library we've encountered an edge case where the library panics. The following is the code to reproduce the issue:

```
 package main

 import (
     "log"
     "time"

     ping "github.com/sparrc/go-ping"
 )

 func main() {

     for {
         pinger, err := ping.NewPinger("www.google.com")
         if err != nil {
             panic(err)
         }
         pinger.Count = 3
         pinger.Timeout = time.Second * 5
         pinger.SetPrivileged(true)
         pinger.Run() // blocks until finished

         if pinger.Statistics().PacketsRecv <= 0 {
             log.Print("ip not responding to pings")
         }

         time.Sleep(2)
     }
 }
```

I've tried to dig into the stacktrace observed as shown below:

```
2017/07/18 04:50:30 http: panic serving 10.60.7.163:42758: runtime error: slice bounds out of range
goroutine 29197 [running]:
net/http.(*conn).serve.func1(0xc42009e700)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x8b2580, 0xc4200100d0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
vendor/github.com/sparrc/go-ping.(*Pinger).processPacket(0xc420362000, 0xc42035c760, 0xc420200b68, 0x1)
vendor/github.com/sparrc/go-ping/ping.go:437 +0x3ab
vendor/github.com/sparrc/go-ping.(*Pinger).run(0xc420362000)
vendor/github.com/sparrc/go-ping/ping.go:310 +0x667
vendor/github.com/sparrc/go-ping.(*Pinger).Run(0xc420362000)
```

My reasoning is as follows:

1. On line: https://github.com/sparrc/go-ping/blob/master/ping.go#L437  if ```pkt.Data``` doesn't have enough bytes inside, the hardcoded constant of ```timeSliceLength``` https://github.com/sparrc/go-ping/blob/master/ping.go#L63 is going to make it go out of range.
2. This could be handled better if a check like this is performed:
   a) ```pkt.Data[]``` is verified before it's evaluated with ```timeSliceLength``` to avoid panic.
   b) Better validate if a pkt is of type ```*icmp.Echo``` before it's used. Is there something else besides ```m.Body.(type)``` that can reveal this information? 

Any ideas what would be the best way to solve this? Let me know if you need any additional details in order to repro this. Happy to help.

**Comment by simar7** [comment]
Any update on this?

**Comment by lstep** [comment]
I got exactly the same error.

**Comment by sparrc** [comment]
sorry for the long delay, I'm going to close because this has since been fixed.
