### ISSUE TITLE
CPU utilization problem

### ISSUE THREAD

**Issue by ascotan** [sparrc/go-ping#13]
There is a problem with CPU utilization on the for/select block on line 293 of ping.go.  Essentially when you have a large number of pingers running the "default" case causes the for loop to spin up the CPU.  I had 700% CPU utilization on my mac.  

The fix for this seems to be to move the default case outside of the select block.  I haven't tested all the permutations here.

```
	for {
		select {
		case <-c:
			close(p.done)
		case <-p.done:
			wg.Wait()
			return
		case <-timeout.C:
			close(p.done)
			wg.Wait()
			return
		case <-interval.C:
			err = p.sendICMP(conn)
			if err != nil {
				fmt.Println("FATAL: ", err.Error())
			}
		case r := <-recv:
			err := p.processPacket(r)
			if err != nil {
				fmt.Println("FATAL: ", err.Error())
			}
		}
                // moved outside of the select block
		if p.Count > 0 && p.PacketsRecv >= p.Count {
			close(p.done)
			wg.Wait()
			return
		}
	}
```

**Comment by Pascougnou** [comment]
After some investigation I think you should also close your tickers otherwise it will eat all your CPU over time. 
cf https://github.com/SewanDevs/go-ping/commit/42df0c56848c82e922339d91aa4d8aa8ed101cf4
