### ISSUE TITLE
On windows 10 , error: The requested protocol has not been configured into the system

### ISSUE THREAD

**Issue by hicaoc** [sparrc/go-ping#17]
PING www.google.com (64.233.189.103):
Error listening for ICMP packets: socket: The requested protocol has not been configured into the system, or no implementation for it exists.

**Comment by SmaugTheGreat** [comment]
I'm not a networking expert, but according to this: https://msdn.microsoft.com/en-us/library/windows/desktop/ms740506(v=vs.85).aspx Windows doesn't allow ICMP messages over UDP. Setting `SetPrivileged(true)` on Windows will workaround this problem by using ICMP over IP.

**Comment by sparrc** [comment]
I believe this is now explained in the README: https://github.com/sparrc/go-ping#note-on-windows-support
