### ISSUE TITLE
go-ping does not work when SetPrivileged(false)

### ISSUE THREAD

**Issue by isi-lincoln** [sparrc/go-ping#31]
A bug was introduced in https://github.com/sparrc/go-ping/commit/d046b245186684963b4d7e3fca8dc4b1538c976a

The following code is responsible:
```
	// Check if reply from same ID
	body := m.Body.(*icmp.Echo)
	if body.ID != p.id {
		return nil
	}
```

This code breaks when SetPrivileged(false) because the kernel is responsible for setting body.ID:

So even if I set the ID in the code, the [kernel's ping_table](https://lwn.net/Articles/443051/) will set it based on the value in the ping_table.
```
Send Echo: &icmp.Echo{ID:1234, Seq:1, Data:[]uint8{0x31, 0x32, 0x33}}
Receive Echo: &icmp.Echo{ID:12655, Seq:1, Data:[]uint8{0x31, 0x32, 0x33}}
```

So checking the ID will fail due to the mismatching IDs.

**Comment by sparrc** [comment]
closed by #32
