### ISSUE TITLE
Like a memory leak

### ISSUE THREAD

**Issue by etimes2008** [sparrc/go-ping#35]
Like a memory leak
I keep looping around, and memory keeps increasing
like：
for {
		pinger, err := ping.NewPinger("192.168.80.2")
		pinger.SetPrivileged(true)
		if err != nil {
			panic(err)
		}
		pinger.Count = 2
		pinger.Timeout = 10 * time.Millisecond
		pinger.Run() // blocks until finished
		stats := pinger.Statistics()
		fmt.Println(len(stats.Rtts) == 0)
		time.Sleep(time.Millisecond * 1)
	}

**Comment by sparrc** [comment]
Thank you for the report, this should be fixed by #40
