### ISSUE TITLE
"Error listening for ICMP packets: socket: permission denied" while using this library in unprivileged ping

### ISSUE THREAD

**Issue by supriya3047** [sparrc/go-ping#4]
This library , when I am using for unprivileged ping throws "Error listening for ICMP packets: socket: permission denied" error with go version go1.7.4 .
what I am doing is-

func (p *Ping) doPing() (latency, jitter, packetLoss float64, err error) {
       

        timeout := time.Second*1000
        interval := time.Second
        count := 5
        host := p.ipAddr
        pinger, cmdErr := ping.NewPinger(host)
        if cmdErr != nil {
                glog.Error("Failed to ping " + p.ipAddr)
                err = cmdErr
                return
        }

        pinger.OnRecv = func(pkt *ping.Packet) {
                fmt.Println("receiving ICMP packets")
        }
        pinger.OnFinish = func(stats *ping.Statistics) {
                fmt.Println("--- %s ping statistics ---", stats.Addr)
                fmt.Println("%d pakets transmitted, %d packets received, %v%% packet loss",
                        stats.PacketsSent, stats.PacketsRecv, stats.PacketLoss)
                fmt.Println("round-trip - min %d ,avg %d ,max %d ,stddev %d",
                        stats.MinRtt, stats.AvgRtt, stats.MaxRtt, stats.StdDevRtt)
        }

        pinger.Count = count
        pinger.Interval = interval
        pinger.Timeout = timeout
        pinger.SetPrivileged(false)
        pinger.Run()
        stats := pinger.Statistics()
        latency = float64(stats.AvgRtt)  
        jitter = float64(stats.StdDevRtt)
        packetLoss = stats.PacketLoss
        return
}

**Comment by workhardcc** [comment]
I have the same issue

**Comment by workhardcc** [comment]
sudo sysctl -w net.ipv4.ping_group_range="0   2147483647"

But I want  use it in docker container...

**Comment by jwriteclub** [comment]
Unfortunately, given the nature of linux this will not be easily solved.

It would be nice if a distinct error was thrown in this situation, in order to allow capturing and informing the user that permissions are wrong, or otherwise handling it automatically.

**Comment by fancy-nie** [comment]
On Mac, it could use unprivileged, but on some Linux, you should use privileged and have sudo permission.

**Comment by cbluth** [comment]
> On Mac, it could use unprivileged, but on some Linux, you should use privileged and have sudo permission.

I am experiencing this issue on ubuntu 18.04 with or without using sudo

**Comment by sparrc** [comment]
I believe the issue here is spelled out in https://github.com/sparrc/go-ping#note-on-linux-support.

Unfortunately the default linux `ping` command runs with special permissions that allows regular users to send ICMP packets. This is not possible to solve for an arbitrary go library so there's nothing this library can do about it.
