### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by g0rbe** [sparrc/go-ping#61]
Hi!

I have the same issue, as in #47 

Here is my simple code:
```
package main

import (
    "github.com/sparrc/go-ping"
)

func main() {
    pinger, err := ping.NewPinger("google.com")
    if err != nil {
            panic(err)
    }
    pinger.SetPrivileged(true)
    pinger.Count = 3
    pinger.Run()
}
```

And the error:
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/sparrc/go-ping.(*Pinger).processPacket(0xc0000929c0, 0xc0000fa090, 0x4, 0x3)
	/home/g0rbe/go/src/github.com/sparrc/go-ping/ping.go:460 +0x828
github.com/sparrc/go-ping.(*Pinger).run(0xc0000929c0)
	/home/g0rbe/go/src/github.com/sparrc/go-ping/ping.go:331 +0x500
github.com/sparrc/go-ping.(*Pinger).Run(...)
	/home/g0rbe/go/src/github.com/sparrc/go-ping/ping.go:278
main.main()
```

Your sample (cmd/ping/ping) also panic.

(Fresh download, executed as root, running on Arch linux)

**Comment by sparrc** [comment]
thanks for the report, was there any other logging you could include?

**Comment by sparrc** [comment]
Also, could you let me know what commit of go-ping you are using?

**Comment by g0rbe** [comment]
The last commit:
`commit e33cfb8ae7ed4ebbfd07bad9d9994f466c6f4b2e (HEAD -> master, origin/master, origin/HEAD)`

No more log, sorry. Played around a litle bit with your package, but `Run()` panicked every time.

**Comment by sparrc** [comment]
I haven't been able to reproduce on Ubuntu, Arch linux, or macOS. Any chance you might be able to checkout commit ee05482e79cc5735587148b93c6770cff67a3081 and give it a test? See PR #62

**Comment by g0rbe** [comment]
Google responded, it works now, thanks for your fast fix! :)

**Comment by sparrc** [comment]
I'm going to leave this open until #62 is merged

**Comment by chn-lee-yumi** [comment]
Hello, this bug can be reproduce on Debian, but it's probabilistic. Not all the time it will panic, but most time. Another information I found is, when you use nohup to run it, it panic more times than just run it on terminal.
