### ISSUE TITLE
TTL is zero on Windows

### ISSUE THREAD

**Issue by chn-lee-yumi** [sparrc/go-ping#67]
Pinger works. All is fine except TTL is zero. The system is windows 10.

**Comment by chn-lee-yumi** [comment]
I tried the same code on MacOS and Linux, it has right TTL.

**Comment by glinton** [comment]
Lack of windows supporting TTL is an upstream deficiency, see [here](https://github.com/golang/net/blob/master/ipv4/payload_nocmsg.go#L15-L23) and [here](https://github.com/golang/net/blob/master/ipv4/control_windows.go#L9-L12)

**Comment by glinton** [comment]
Track the issue at https://github.com/golang/go/issues/7175 and 7174

**Comment by chn-lee-yumi** [comment]
Thanks!
