### ISSUE TITLE
[Question] Can go-ping be used as an ICMP listener only?

### ISSUE THREAD

**Issue by noam09** [sparrc/go-ping#73]
First off, this is an awesome library!
The title pretty much says it all. I'd like to set up an ICMP listener (and logger) on Windows. 
Can go-ping be used for this purpose?

**Comment by sparrc** [comment]
It cannot be used for this, but if you want to write a listener yourself you might want to look at the code here: https://github.com/sparrc/go-ping/blob/master/ping.go#L397
