### ISSUE TITLE
memory leak ?

### ISSUE THREAD

**Issue by jacobluo** [sparrc/go-ping#8]
i wrote a ping service program, it's will ping a lot of servers every period.
i found the memory of program increased unlimited.

init ping.NewPinger when ping a ip

please help ?
![ping_agent](https://cloud.githubusercontent.com/assets/841868/26536923/c4558ad4-446d-11e7-8831-412e681a95cb.png)
![ping_agent2](https://cloud.githubusercontent.com/assets/841868/26536924/c45aba9a-446d-11e7-95fd-855bcbf27054.png)

**Comment by simar7** [comment]
I tried reproducing this but had no luck. Maybe it's been fixed since you filed this bug?

**Comment by jacobluo** [comment]
thanks a lot.

**Comment by sparrc** [comment]
Thank you for the report, I believe this has been fixed by #40
